[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dlogger"
version = "0.1.0"
description = "Personal simple logger"
dependencies = [
    "termcolor",
]

[tool.setuptools.packages.find]
where = ["."]